# Generated by Django 5.2.7 on 2025-11-17 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='connection',
            index=models.Index(fields=['user1', 'user2'], name='api_connect_user1_i_5737e2_idx'),
        ),
        migrations.AddIndex(
            model_name='matchaction',
            index=models.Index(fields=['actor', 'target', 'action'], name='api_matchac_actor_i_571400_idx'),
        ),
    ]
