# Generated by Django 5.2.7 on 2025-12-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connection_api_connect_user1_i_5737e2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
